services:
  gateway:
    build: .
    ports: 
     - "2080:80"
    
  auth-api:
    build: ./../RentRide.AuthenticationApi/
    ports: 
      - "6565:80"
    depends_on:
      - "auth-api-db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=(localdb)\mssqllocaldb;Database=Authentication;User=SA;Password=RentRide-auth-api22
  
  auth-api-db:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    ports:
      - "3210:1234"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RentRide-auth-api22
        
  user-api:
    build: ./../RentRide.UserApi/
    ports:
      - "2245:80"
    depends_on: 
      - "user-api-db"
  
  user-api-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "3345:5433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RentRide-usr-api22
        
  client:
    build: ./../RentRide.Client/client/
    ports: 
      - "6500:80"
    